name: EC2에 배포

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          command_timeout: 2m # 2분으로 단축
          script: |
            # 코드 업데이트
            cd /home/ubuntu/lumi-back
            git pull origin main

            # 서버 재시작 (패키지 설치 생략)
            pkill -f "uvicorn" || true
            sleep 2

            source venv/bin/activate
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &

            # 시작 확인
            sleep 3
            if curl -s http://localhost:8000/ping > /dev/null; then
              echo "✅ 배포 성공!"
            else
              echo "❌ 배포 실패"
              exit 1
            fi
