name: EC2에 배포

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          command_timeout: 2m
          script: |
            cd /home/ubuntu/lumi-back
            git pull origin main

            # PID 파일로 안전하게 종료
            if [ -f "uvicorn.pid" ]; then
              echo "기존 서버 종료 중..."
              kill $(cat uvicorn.pid) 2>/dev/null || true
              rm -f uvicorn.pid
              sleep 2
            fi

            source venv/bin/activate

            # PID 저장하면서 서버 시작
            uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &
            echo $! > uvicorn.pid

            sleep 3

            if curl -s http://localhost:8000/ping > /dev/null; then
              echo "✅ 배포 성공! PID: $(cat uvicorn.pid)"
            else
              echo "❌ 배포 실패"
              exit 1
            fi
