name: EC2에 배포

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          command_timeout: 3m
          script: |
            echo "=== 1. 디렉토리 이동 ==="
            cd /home/ubuntu/lumi-back || { echo "디렉토리 이동 실패"; exit 1; }
            echo "현재 위치: $(pwd)"

            echo "=== 2. Git pull ==="
            git pull origin main
            echo "Git pull 완료"

            echo "=== 3. 현재 프로세스 확인 ==="
            ps aux | grep uvicorn | grep -v grep || echo "uvicorn 프로세스 없음"

            echo "=== 4. 프로세스 종료 시도 ==="
            pkill -f "uvicorn" || echo "종료할 프로세스 없음"
            echo "프로세스 종료 완료"

            echo "=== 5. 2초 대기 ==="
            sleep 2
            echo "대기 완료"

            echo "=== 6. 가상환경 활성화 ==="
            if [ -d "venv" ]; then
              echo "venv 디렉토리 존재함"
              source venv/bin/activate || { echo "가상환경 활성화 실패"; exit 1; }
              echo "가상환경 활성화 완료"
            else
              echo "venv 디렉토리 없음"
              exit 1
            fi

            echo "=== 7. 서버 시작 ==="
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &
            echo "서버 시작 명령 실행 완료"

            echo "=== 8. 3초 대기 ==="
            sleep 3
            echo "대기 완료"

            echo "=== 9. 헬스체크 ==="
            if curl -s http://localhost:8000/ping > /dev/null; then
              echo "✅ 배포 성공!"
            else
              echo "❌ 배포 실패 - 서버 응답 없음"
              echo "앱 로그:"
              tail -n 5 app.log || echo "로그 파일 없음"
              exit 1
            fi

            echo "=== 10. 최종 프로세스 확인 ==="
            ps aux | grep uvicorn | grep -v grep || echo "uvicorn 프로세스 없음"
            echo "✅ 모든 단계 완료"
